[package]
name = "timer_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "timer_core"
path = "src/lib.rs"

[[bin]]
name = "timer"
path = "src/main.rs"

[dependencies]
crossterm = "0.22.1"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["user-hooks"]
